### ISSUE TITLE
undefined error with Hogan.js

### ISSUE THREAD

**Issue by kbingman** [flatiron/viewful#11]
when using hogan.js, the newer versions use the correct "require('hogan')" instead of the previous "require('hogan.js'). This leads to an error when compiling hogan.js templates with viewful and a current copy of hogan.

**Comment by Marak** [comment]
Thanks for the feedback!

Would you be able to get a pull request open for this?

**Comment by eschmitt** [comment]
when I installed hogan using:

``` javascript
npm install hogan
```

The package.json file shows a version of 1.0.5-dev.

However, when I install Hogan using: 

``` javascript
npm install hogan.js
```

The package file shows a version of 2.0.0

Both of these package files point to the same repository url https://github.com/twitter/hogan.js.git, which is showing version 3.0.0... Not sure where the disconnect is happening, but its weird.

This same issue was filed with Consolidate.js (https://github.com/visionmedia/consolidate.js/issues/54) and was closed without changing anything. Not sure what's going on, maybe Twitter hasn't published the latest release correctly to npm?

**Comment by eschmitt** [comment]
@kbingman, are you installing Hogan with npm? And if so, how are you getting the latest version? Are you just grabbing the latest version from github instead of npm?

Looking at Twitter's Hogan site, http://twitter.github.com/hogan.js/, they install and require as follows:

``` javascript
npm install hogan.js

var hogan = require(hogan.js);
```

**Comment by eschmitt** [comment]
FYI:

https://github.com/twitter/hogan.js/issues/87
https://github.com/twitter/hogan.js/issues/103

**Comment by eschmitt** [comment]
@Marak, I'm not sure if I did this correctly... The fix is in a separate branch called "hogan-require-fix". I wanted you to be able to review it before it was merged into master.

**Comment by eschmitt** [comment]
@Marak, I didn't realize that referencing the issue in a git commit message closed the issue... Re-opened it so you could review and possibly merge with the master branch. The fix is in a separate branch called "hogan-require-fix". Sorry for the mix-up..

**Comment by eschmitt** [comment]
@kbingman, I just merged the fix into the master branch. Sorry for such a long delay. I was waiting for some feedback on whether we wanted to support an unreleased version of hogan.js. The fix has not been published to npm, so you will need to clone the project from github if you want to use it in your project.
